name: Run Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ["1.21", "1.20", "1.18", "1.19"]

    runs-on: ubuntu-20.04

    name: Go ${{ matrix.go }} Tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run Test
        run: go test -p 1 -v ./...

      - name: Run Coverage
        run: go test -p 1 -v -cover ./...
